//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Pismo
    {
        public int ID_Posiljke { get; set; }
        public bool Preporuceno { get; set; }
    
        public virtual PostanskaUsluga PostanskaUsluga { get; set; }
    }
}
