//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PostaDbContainer : DbContext
    {
        public PostaDbContainer()
            : base("name=PostaDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Skladiste> Skladista { get; set; }
        public virtual DbSet<Radnik> Radnici { get; set; }
        public virtual DbSet<Postar> Postari { get; set; }
        public virtual DbSet<Posta> Poste { get; set; }
        public virtual DbSet<Sluzbenik> Sluzbenici { get; set; }
        public virtual DbSet<PostanskaUsluga> PostanskeUsluge { get; set; }
        public virtual DbSet<Paket> Pakets { get; set; }
        public virtual DbSet<Pismo> Pismoes { get; set; }
        public virtual DbSet<FinansijskaUsluga> FinansijskaUslugas { get; set; }
        public virtual DbSet<Uplatnica> Uplatnicas { get; set; }
        public virtual DbSet<PostNet> PostNets { get; set; }
    }
}
