//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Radnik
    {
        public int JMBG_Radnika { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int PostaPostanskiBroj { get; set; }
    
        public virtual Postar Postar { get; set; }
        public virtual Posta Posta { get; set; }
        public virtual Sluzbenik Sluzbenik { get; set; }
    }
}
