//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Uplatnica
    {
        public int ID_Uplate { get; set; }
        public long BrojRacuna { get; set; }
    
        public virtual FinansijskaUsluga FinansijskaUsluga { get; set; }
    }
}
